import { createTheme, createThemeContract, style } from '@vanilla-extract/css';
import { themes } from 'prism-react-renderer';
import { defaults } from './defaults.css';

const contract = {
  a: { color: null },
  badge: { backgroundColor: null },
  blockquote: { color: null },
  em: { color: null },
  h1: { color: null },
  h2: { color: null },
  h3: { color: null },
  h4: { color: null },
  h5: { color: null },
  h6: { color: null },
  li: { color: null },
  ol: { color: null },
  p: { color: null },
  strong: { color: null },
  ul: { color: null },
};

export const themeContract = createThemeContract(contract);

const themeNames = [
  'PLAIN_DARK',
  'TRUE_LOVE',
  'SHADES_OF_PURPLE',
  'SHADES_OF_GREEN',
  'PLAIN_LIGHT',
  'AUTUMN_DUSK',
  'NORDIC_BLUES',
  'FUNKY_TOWN',
  'CANDY_CRUSH',
  'GENTLE_GRAPE',
] as const;

type Themes = {
  [key in (typeof themeNames)[number]]: {
    prismTheme: keyof typeof themes;
    nodes: string;
  };
};

export const customThemes: Themes = {
  PLAIN_DARK: {
    prismTheme: 'vsDark',
    nodes: createTheme(themeContract, {
      a: { color: '#bdbdbd' },
      badge: { backgroundColor: '#636363' },
      blockquote: { color: '#a9a9a9' },
      em: { color: '#919191' },
      h1: { color: '#757575' },
      h2: { color: '#848484' },
      h3: { color: '#a3a3a3' },
      h4: { color: '#c2c2c2' },
      h5: { color: '#d1d1d1' },
      h6: { color: '#e0e0e0' },
      li: { color: '#9e9e9e' },
      ol: { color: '#9e9e9e' },
      p: { color: '#9e9e9e' },
      strong: { color: '#ffffff' },
      ul: { color: '#9e9e9e' },
    }),
  },
  TRUE_LOVE: {
    prismTheme: 'synthwave84',
    nodes: createTheme(themeContract, {
      a: { color: '#ff8fa3' },
      badge: { backgroundColor: '#590d22' },
      blockquote: { color: '#fff0f3' },
      em: { color: '#ff8fa3' },
      h1: { color: '#800f2f' },
      h2: { color: '#a4133c' },
      h3: { color: '#c9184a' },
      h4: { color: '#ff4d6d' },
      h5: { color: '#ff758f' },
      h6: { color: '#ff8fa3' },
      li: { color: '#fff0f3' },
      ol: { color: '#fff0f3' },
      p: { color: '#fff0f3' },
      strong: { color: '#ff8fa3' },
      ul: { color: '#fff0f3' },
    }),
  },
  SHADES_OF_PURPLE: {
    prismTheme: 'shadesOfPurple',
    nodes: createTheme(themeContract, {
      a: { color: '' },
      badge: { backgroundColor: '#90c7de' },
      blockquote: { color: '' },
      em: { color: '#afacf7' },
      h1: { color: '#3c42c4' },
      h2: { color: '#6366f1' },
      h3: { color: '#a3a5f7' },
      h4: { color: '#c1a5f5' },
      h5: { color: '#e4a6ed' },
      h6: { color: '#90c7de' },
      li: { color: '#bfe8ff' },
      ol: { color: '#bfe8ff' },
      p: { color: '#bfe8ff' },
      strong: { color: '#ad86f1' },
      ul: { color: '#bfe8ff' },
    }),
  },
  SHADES_OF_GREEN: {
    prismTheme: 'github',
    nodes: createTheme(themeContract, {
      a: { color: '#547f7c' },
      badge: { backgroundColor: '#869f88' },
      blockquote: { color: '' },
      em: { color: '#547f7c' },
      h1: { color: '#0A5C36' },
      h2: { color: '#216229' },
      h3: { color: '#236f4c' },
      h4: { color: '#167e8c' },
      h5: { color: '#9ca585' },
      h6: { color: '#869f88' },
      li: { color: '#849bb3' },
      ol: { color: '#849bb3' },
      p: { color: '#849bb3' },
      strong: { color: '#547f7c' },
      ul: { color: '#849bb3' },
    }),
  },
  PLAIN_LIGHT: {
    prismTheme: 'vsLight',
    nodes: createTheme(themeContract, {
      a: { color: '' },
      badge: { backgroundColor: '#7a7d84' },
      blockquote: { color: '' },
      em: { color: '' },
      h1: { color: '#222222' },
      h2: { color: '#3f3e3e' },
      h3: { color: '#36363a' },
      h4: { color: '#7f7b7f' },
      h5: { color: '#858389' },
      h6: { color: '#7a7d84' },
      li: { color: '#686e70' },
      ol: { color: '#686e70' },
      p: { color: '#686e70' },
      strong: { color: '' },
      ul: { color: '#686e70' },
    }),
  },
  AUTUMN_DUSK: {
    prismTheme: 'duotoneLight',
    nodes: createTheme(themeContract, {
      a: { color: '#e2a478' },
      badge: { backgroundColor: '#b46649' },
      blockquote: { color: '#e2a478' },
      em: { color: '#c17d5c' },
      h1: { color: '#a85f3f' },
      h2: { color: '#b46649' },
      h3: { color: '#c17d5c' },
      h4: { color: '#cd9470' },
      h5: { color: '#daab85' },
      h6: { color: '#e7c29a' },
      li: { color: '#eedbc0' },
      ol: { color: '#eedbc0' },
      p: { color: '#eedbc0' },
      strong: { color: '#e2a478' },
      ul: { color: '#eedbc0' },
    }),
  },
  NORDIC_BLUES: {
    prismTheme: 'nightOwl',
    nodes: createTheme(themeContract, {
      a: { color: '#6f9fb9' },
      badge: { backgroundColor: '#25495d' },
      blockquote: { color: '#6f9fb9' },
      em: { color: '#6f9fb9' },
      h1: { color: '#1e3440' },
      h2: { color: '#25495d' },
      h3: { color: '#335d6a' },
      h4: { color: '#4f7b9b' },
      h5: { color: '#6893ab' },
      h6: { color: '#82a8bc' },
      li: { color: '#b7ced7' },
      ol: { color: '#b7ced7' },
      p: { color: '#b7ced7' },
      strong: { color: '#6f9fb9' },
      ul: { color: '#b7ced7' },
    }),
  },
  FUNKY_TOWN: {
    prismTheme: 'synthwave84',
    nodes: createTheme(themeContract, {
      a: { color: '#e91e63' },
      badge: { backgroundColor: '#ff9800' },
      blockquote: { color: '#9c27b0' },
      em: { color: '#673ab7' },
      h1: { color: '#3f51b5' },
      h2: { color: '#2196f3' },
      h3: { color: '#03a9f4' },
      h4: { color: '#00bcd4' },
      h5: { color: '#009688' },
      h6: { color: '#4caf50' },
      li: { color: '#cddc39' },
      ol: { color: '#cddc39' },
      p: { color: '#cddc39' },
      strong: { color: '#ffeb3b' },
      ul: { color: '#cddc39' },
    }),
  },
  CANDY_CRUSH: {
    prismTheme: 'oceanicNext',
    nodes: createTheme(themeContract, {
      a: { color: '#ff69b4' },
      badge: { backgroundColor: '#ff6347' },
      blockquote: { color: '#ff1493' },
      em: { color: '#db7093' },
      h1: { color: '#ff6347' },
      h2: { color: '#ff4500' },
      h3: { color: '#ff8c00' },
      h4: { color: '#ffa07a' },
      h5: { color: '#ffa500' },
      h6: { color: '#ffd700' },
      li: { color: '#ffb6c1' },
      ol: { color: '#ffb6c1' },
      p: { color: '#ffb6c1' },
      strong: { color: '#ff69b4' },
      ul: { color: '#ffb6c1' },
    }),
  },
  GENTLE_GRAPE: {
    prismTheme: 'duotoneDark',
    nodes: createTheme(themeContract, {
      a: { color: '#cfa7da' },
      badge: { backgroundColor: '#7c5295' },
      blockquote: { color: '#cfa7da' },
      em: { color: '#cfa7da' },
      h1: { color: '#7c5295' },
      h2: { color: '#8d5fa6' },
      h3: { color: '#9e6cb7' },
      h4: { color: '#af79c8' },
      h5: { color: '#c085d9' },
      h6: { color: '#d19eea' },
      li: { color: '#e7d7f2' },
      ol: { color: '#e7d7f2' },
      p: { color: '#e7d7f2' },
      strong: { color: '#cfa7da' },
      ul: { color: '#e7d7f2' },
    }),
  },
};

export type Styles = Partial<Record<keyof typeof defaults | keyof typeof contract, string>>;

export const styles: Styles = {
  a: style([defaults.a, { ...themeContract.a }]),
  blockquote: style([defaults.blockquote, { ...themeContract.blockquote }]),
  code: defaults.code,
  clipboard: defaults.clipboard,
  em: style([defaults.em, { ...themeContract.em }]),
  h1: style([defaults.h1, { color: themeContract.h1.color }]),
  h2: style([defaults.h2, { ...themeContract.h2 }]),
  h3: style([defaults.h3, { ...themeContract.h3 }]),
  h4: style([defaults.h4, { ...themeContract.h4 }]),
  h5: style([defaults.h5, { ...themeContract.h5 }]),
  h6: style([defaults.h6, { ...themeContract.h6 }]),
  inlinecode: defaults.inlinecode,
  li: style([{ ...themeContract.li }]),
  metadata: defaults.metadata,
  p: style([defaults.p, { ...themeContract.p }]),
  strong: style([defaults.strong, { ...themeContract.strong }]),
  ul: style([defaults.ul, { ...themeContract.ul }]),
  badge: style([defaults.badge, { ...themeContract.badge }]),
};
